export enum CosmeticType {
  EMOJI = 'emoji',
  WRAP = 'wrap',
  GLIDER = 'glider',
  CONTRAIL = 'contrail',
  TOY = 'toy',
  SPRAY = 'spray',
  PICKAXE = 'pickaxe',
  AURA = 'aura',
  SHOE = 'shoe',
  PET = 'pet',
  MUSIC = 'music',
  LOADINGSCREEN = 'loadingscreen',
  EMOTE = 'emote',
  PETCARRIER = 'petcarrier',
  OUTFIT = 'outfit',
  SIDEKICK = 'sidekick',
  BACKPACK = 'backpack',
  BANNER = 'banner',
  UNKNOWN = 'unknown',
}
