export enum Rarity {
  COMMON = 'common',
  UNCOMMON = 'uncommon',
  RARE = 'rare',
  EPIC = 'epic',
  LEGENDARY = 'legendary',
  MYTHIC = 'mythic',
  GAMINGLEGENDS = 'gamingLegends',
  ICON = 'icon',
  MARVEL = 'marvel',
  DC = 'dc',
  STARWARS = 'starWars',
  SHADOW = 'shadow',
  SLURP = 'slurp',
  DARK = 'dark',
  FROZEN = 'frozen',
  LAVA = 'lava',
  UNKNOWN = 'unknown',
}
